on:
  push:
    branches:
      - main

name: Deploy RFC Docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install ğŸ¦€
        run: |
          curl -L https://github.com/badboy/mdbook-mermaid/releases/download/v0.13.0/mdbook-mermaid-v0.13.0-x86_64-unknown-linux-gnu.tar.gz | tar xvz
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.36/mdbook-v0.4.36-x86_64-unknown-linux-gnu.tar.gz | tar xvz
          export PATH=$PATH:$(pwd)
          mdbook --version
          mdbook-mermaid --version

      - name: Build ğŸ› 
        run: |
          export PATH=$PATH:$(pwd)
          mdbook test
          mdbook build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: book
          commit-message: "[skip ci] deploy gh-pages"
